Repository sony/flutter-embedded-linux, pull requests merged in 2021-05, with the labels that each got.

#107 Fix typos in READMEs
  doc/README.md
  meta-flutter/README.md
Labels: documentation

#111 Add recipe flutter engine.
  meta-flutter/README.md
  meta-flutter/recipes-graphics/flutter-engine/flutter-engine.bb
  meta-flutter/recipes-graphics/flutter-engine/gn-args-utils.inc
Labels: yocto

#104 Support to resize on DRM-GBM backend.
  src/flutter/shell/platform/linux_embedded/surface/linuxes_surface.cc
  src/flutter/shell/platform/linux_embedded/surface/linuxes_surface.h
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_drm.h
  src/flutter/shell/platform/linux_embedded/window/native_window.h
  src/flutter/shell/platform/linux_embedded/window/native_window_drm.h
  src/flutter/shell/platform/linux_embedded/window/native_window_drm_gbm.cc
  src/flutter/shell/platform/linux_embedded/window/native_window_drm_gbm.h
Labels: drm-backend

#114 Update README: objective, features
  README.md
Labels: documentation

#115 Fix weston desktop shell version issue
  cmake/package.cmake
  doc/README.md
  examples/flutter-weston-desktop-shell-virtual-keyboard/main.cc
  examples/flutter-weston-desktop-shell/main.cc
  src/templates/app/linux-wayland-weston-desktop-shell/main.cc
Labels: bug, wayland-backend

#116 Update README: RB5 status, etc
  README.md
Labels: documentation

#117 Update README: fix tested device table
  README.md
Labels: documentation

#119 Fix a bug that fails to create an offscreen surface for drm-gbm
  src/flutter/shell/platform/linux_embedded/surface/context_egl.cc
  src/flutter/shell/platform/linux_embedded/surface/linuxes_surface.cc
  src/flutter/shell/platform/linux_embedded/surface/linuxes_surface.h
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_drm.h
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_x11.cc
  src/flutter/shell/platform/linux_embedded/window/native_window.h
  src/flutter/shell/platform/linux_embedded/window/native_window_drm.cc
  src/flutter/shell/platform/linux_embedded/window/native_window_drm.h
  src/flutter/shell/platform/linux_embedded/window/native_window_drm_eglstream.cc
  src/flutter/shell/platform/linux_embedded/window/native_window_drm_eglstream.h
  src/flutter/shell/platform/linux_embedded/window/native_window_drm_gbm.cc
  src/flutter/shell/platform/linux_embedded/window/native_window_wayland.cc
Labels: bug, drm-backend

#120 Support text input protocol v3 for onscreen keyboards on Wayland
  cmake/build.cmake
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.h
Labels: keyboard, wayland-backend

#122 Rename wl_pointer in CursorInfo
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.h
Labels: bug, wayland-backend

#123 Update README: add disable-desktop-embeddings option
  doc/building-engine-embedder.md
Labels: documentation

#129 Fixed bug regarding the display of Wayland's on-screen keyboard
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.h
Labels: bug, keyboard, wayland-backend

#131 Fixed bug blocking events from flutter engine for Wayland
  examples/flutter-drm-eglstream-backend/main.cc
  examples/flutter-drm-gbm-backend/main.cc
  examples/flutter-external-texture-plugin/main.cc
  examples/flutter-wayland-client/main.cc
  examples/flutter-weston-desktop-shell-virtual-keyboard/main.cc
  examples/flutter-weston-desktop-shell/main.cc
  examples/flutter-x11-client/main.cc
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc
  src/templates/app/linux-drm/main.cc
  src/templates/app/linux-wayland-weston-desktop-shell/main.cc
  src/templates/app/linux-wayland/main.cc
  src/templates/app/linux-x11/main.cc
Labels: bug, wayland-backend

#140 Add vsync wayland support
  cmake/build.cmake
  examples/flutter-drm-eglstream-backend/flutter_window.cc
  examples/flutter-drm-gbm-backend/flutter_window.cc
  examples/flutter-external-texture-plugin/flutter_window.cc
  examples/flutter-wayland-client/flutter_window.cc
  examples/flutter-weston-desktop-shell-virtual-keyboard/flutter_window.cc
  examples/flutter-weston-desktop-shell/flutter_window.cc
  examples/flutter-x11-client/flutter_window.cc
  src/client_wrapper/include/flutter/flutter_view.h
  src/flutter/shell/platform/linux_embedded/flutter_linuxes.cc
  src/flutter/shell/platform/linux_embedded/flutter_linuxes_engine.cc
  src/flutter/shell/platform/linux_embedded/flutter_linuxes_engine.h
  src/flutter/shell/platform/linux_embedded/flutter_linuxes_view.cc
  src/flutter/shell/platform/linux_embedded/flutter_linuxes_view.h
  src/flutter/shell/platform/linux_embedded/public/flutter_linuxes.h
  src/flutter/shell/platform/linux_embedded/vsync_waiter.cc
  src/flutter/shell/platform/linux_embedded/vsync_waiter.h
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_drm.h
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.h
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_x11.cc
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_x11.h
  src/flutter/shell/platform/linux_embedded/window_binding_handler.h
  src/flutter/shell/platform/linux_embedded/window_binding_handler_delegate.h
  src/templates/app/common/flutter_window.cc
Labels: wayland

#142 Update README: add description about building for Flutter apps
  README.md
  doc/README.md
Labels: documentation

#146 Add log output of flutter apps
  src/flutter/shell/platform/linux_embedded/flutter_linuxes_engine.cc
Labels: engine

#147 Update .gclient file to not download other than Linux deps
  doc/building-engine-embedder.md
  meta-flutter/recipes-graphics/flutter-engine/flutter-engine.bb
Labels: documentation, yocto

#148 Update the engine common library
  src/flutter/shell/platform/common/client_wrapper/include/flutter/encodable_value.h
  src/flutter/shell/platform/common/client_wrapper/standard_codec.cc
Labels: engine

#149 Bugfix: multi-touch doesn't work correctly
  src/flutter/shell/platform/linux_embedded/flutter_linuxes_view.cc
Labels: bug, drm, touch, wayland, x11

#151 Bugfix setting of frame rate for Wayland
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.cc
Labels: bug, wayland

#152 Add lifecycle plugin
  cmake/build.cmake
  src/flutter/shell/platform/linux_embedded/flutter_linuxes_view.cc
  src/flutter/shell/platform/linux_embedded/flutter_linuxes_view.h
  src/flutter/shell/platform/linux_embedded/logger.cc
  src/flutter/shell/platform/linux_embedded/logger.h
  src/flutter/shell/platform/linux_embedded/plugin/key_event_plugin.cc
  src/flutter/shell/platform/linux_embedded/plugin/lifecycle_plugin.cc
  src/flutter/shell/platform/linux_embedded/plugin/lifecycle_plugin.h
Labels: engine

#153 Add navigation plugin
  cmake/build.cmake
  src/flutter/shell/platform/linux_embedded/flutter_linuxes_view.cc
  src/flutter/shell/platform/linux_embedded/flutter_linuxes_view.h
  src/flutter/shell/platform/linux_embedded/plugin/navigation_plugin.cc
  src/flutter/shell/platform/linux_embedded/plugin/navigation_plugin.h
Labels: engine
