Repository sony/flutter-embedded-linux, pull requests merged in 2021-04, with the labels that each got.

#53 Update README debugging (Reflect feedbacks)
  DEBUGGING.md
  README.md
Labels: documentation

#58 Update README
  README.md
Labels: documentation

#60 Switch XCB to Xlib
  .github/workflows/build-test.yml
  README.md
  cmake/build.cmake
  cmake/package.cmake
  src/flutter/shell/platform/linux_embedded/plugin/key_event_plugin.cc
  src/flutter/shell/platform/linux_embedded/surface/context_egl.h
  src/flutter/shell/platform/linux_embedded/surface/context_egl_x11.h
  src/flutter/shell/platform/linux_embedded/surface/linuxes_surface_gl_x11.cc
  src/flutter/shell/platform/linux_embedded/surface/linuxes_surface_gl_x11.h
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_x11.cc
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_x11.h
  src/flutter/shell/platform/linux_embedded/window/native_window_x11.cc
  src/flutter/shell/platform/linux_embedded/window/native_window_x11.h
Labels: x11-backend

#66 Update README: Added description to get engine version from flutter sdk
  BUILDING-ENGINE-EMBEDDER.md
  README.md
Labels: documentation

#75 Fix DRM related processing of eglstream.
  src/flutter/shell/platform/linux_embedded/window/native_window_drm_eglstream.cc
  src/flutter/shell/platform/linux_embedded/window/native_window_drm_eglstream.h
Labels: drm-backend

#76 Split README and move to doc directory
  README.md
  doc/README.md
  doc/building-engine-embedder.md
  doc/debugging.md
  examples/flutter-drm-eglstream-backend/cmake/user_config.cmake
  examples/flutter-drm-gbm-backend/cmake/user_config.cmake
  examples/flutter-external-texture-plugin/cmake/user_config.cmake
  examples/flutter-wayland-client/cmake/user_config.cmake
  examples/flutter-weston-desktop-shell-virtual-keyboard/cmake/user_config.cmake
  examples/flutter-weston-desktop-shell/cmake/user_config.cmake
  examples/flutter-x11-client/cmake/user_config.cmake
Labels: documentation

#77 Update documents: format and build
  doc/README.md
Labels: documentation

#80 Update doc/README: Fix incorrect install path
  doc/README.md
Labels: documentation

#78 Fix GBM color format
  src/flutter/shell/platform/linux_embedded/window/native_window_drm_gbm.cc
Labels: bug, drm-backend

#72 Add yocto recipes for flutter-embedded-linux
  meta-flutter/README.md
  meta-flutter/conf/layer.conf
  meta-flutter/recipes-graphics/flutter-embedded-linux/dependency.inc
  meta-flutter/recipes-graphics/flutter-embedded-linux/flutter-drm-eglstream-backend.bb
  meta-flutter/recipes-graphics/flutter-embedded-linux/flutter-drm-gbm-backend.bb
  meta-flutter/recipes-graphics/flutter-embedded-linux/flutter-wayland-client.bb
  meta-flutter/recipes-graphics/flutter-embedded-linux/repository.inc
  meta-flutter/recipes-graphics/flutter-embedded-linux/tasks.inc
Labels: yocto

#84 Fix drm error message and create .cc file
  cmake/build.cmake
  src/flutter/shell/platform/linux_embedded/window/native_window_drm.cc
  src/flutter/shell/platform/linux_embedded/window/native_window_drm.h
  src/flutter/shell/platform/linux_embedded/window/native_window_drm_eglstream.cc
  src/flutter/shell/platform/linux_embedded/window/native_window_drm_eglstream.h
  src/flutter/shell/platform/linux_embedded/window/native_window_drm_gbm.cc
  src/flutter/shell/platform/linux_embedded/window/native_window_drm_gbm.h
Labels: drm-backend

#86 Fix yocto recipe of flutter-wayland-client.
  cmake/build.cmake
  meta-flutter/README.md
Labels: yocto

#88 Update README.md
  README.md
Labels: documentation

#89 Update README: the note of DRM for i.mx 8m devices
  README.md
Labels: documentation

#90 Update README: add a link to meta-flutter
  doc/README.md
  meta-flutter/README.md
Labels: documentation

#91 Update README: add description of flutter build for debug mode
  README.md
  doc/README.md
Labels: documentation

#98 Fix keyboard input bug
  src/flutter/shell/platform/linux_embedded/plugin/key_event_plugin.cc
Labels: bug, drm-backend, keyboard

#99 Initialize binding_handler_delegate_ to null
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_drm.h
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_wayland.h
  src/flutter/shell/platform/linux_embedded/window/linuxes_window_x11.h
Labels: bug, drm-backend, wayland-backend, x11-backend
